<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>KOF Online</AssemblyName>
    <RootNamespace>KofOnlineLauncher</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\kyo-background.png" />
    <Resource Include="Assets\kyo-orochi-andrew-background.png" />
    <Resource Include="Assets\ajude-projeto-qrcode.png" />
  </ItemGroup>
</Project>
